name: 'Experiment runner'
inputs:
  task:
    required: true
  variant:
    required: true
  variant-prefix:
    required: true
  experiment-id:
    required: true
  api-key:
    required: true
  repository:
    required: true
  run-id:
    required: true
  jdk_version:
    required: false
    default: 17
  jdk_vendor:
    required: false
    default: "zulu"    
  execution-number:
    required: true 
  mode:
    required: true 
  extra-args:
    required: true  
  cache-url:
    required: false  

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.variant }}
    - uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.jdk_vendor }}
        java-version: ${{ inputs.jdk_version }}
    - name: Set Gradle Cache Excludes
      if: github.event.inputs.mode != 'no caching'    
      id: set-cache-excludes
      run: 
          BUILD_CACHE_ENTRY="caches/build-cache-1"
          TRANSFORM_CACHE_ENTRY="caches/**/transforms"
          MODULES_CACHE_ENTRY="caches/modules-*/*"
          JAR_CACHE_ENTRY="caches/jars-*/*"

          if [[ "${{ inputs.mode }}" == "dependencies cache" ]]; then
            echo "GRADLE_HOME_CACHE_EXCLUDES=$BUILD_CACHE_ENTRY" >> $GITHUB_ENV
          elif [[ "${{ inputs.mode }}" == "dependencies cache - trasnforms cache" ]]; then
            echo "GRADLE_HOME_CACHE_EXCLUDES=$TRANSFORM_CACHE_ENTRY" >> $GITHUB_ENV
          elif [[ "${{ inputs.mode }}" == "remote task cache" ]]; then  
            echo "GRADLE_HOME_CACHE_EXCLUDES<<EOF" >> $GITHUB_ENV
            echo $BUILD_CACHE_ENTRY >> $GITHUB_ENV
            echo $MODULES_CACHE_ENTRY >> $GITHUB_ENV
            echo $JAR_CACHE_ENTRY >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV                     
          elif [[ "${{ inputs.mode }}" == "local task cache" ]]; then  
            echo "GRADLE_HOME_CACHE_EXCLUDES<<EOF" >> $GITHUB_ENV
            echo $MODULES_CACHE_ENTRY >> $GITHUB_ENV
            echo $JAR_CACHE_ENTRY >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV                     
          elif [[ "${{ inputs.mode }}" == "local task cache + dependencies cache" ]]; then  
            echo "GRADLE_HOME_CACHE_EXCLUDES=''" >> $GITHUB_ENV
          elif [[ "${{ inputs.mode }}" == "remote task cache + dependencies cache" ]]; then  
            echo "GRADLE_HOME_CACHE_EXCLUDES='$BUILD_CACHE_ENTRY'" >> $GITHUB_ENV
          elif [[ "${{ inputs.mode }}" == "remote task cache - transforms cache" ]]; then  
            echo "GRADLE_HOME_CACHE_EXCLUDES<<EOF" >> $GITHUB_ENV
            echo $BUILD_CACHE_ENTRY >> $GITHUB_ENV
            echo $MODULES_CACHE_ENTRY >> $GITHUB_ENV
            echo $JAR_CACHE_ENTRY >> $GITHUB_ENV
            echo $TRANSFORM_CACHE_ENTRY >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV                     
          elif [[ "${{ inputs.mode }}" == "local task cache - transforms cache" ]]; then  
            echo "GRADLE_HOME_CACHE_EXCLUDES<<EOF" >> $GITHUB_ENV
            echo $TRANSFORM_CACHE_ENTRY >> $GITHUB_ENV
            echo $MODULES_CACHE_ENTRY >> $GITHUB_ENV
            echo $JAR_CACHE_ENTRY >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV                     
          elif [[ "${{ inputs.mode }}" == "local task cache + dependencies cache - transforms cache" ]]; then  
            echo "GRADLE_HOME_CACHE_EXCLUDES<<EOF" >> $GITHUB_ENV
            echo $TRANSFORM_CACHE_ENTRY >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV                     
          elif [[ "${{ inputs.mode }}" == "remote task cache + dependencies cache - transforms cache" ]]; then  
            echo "GRADLE_HOME_CACHE_EXCLUDES<<EOF" >> $GITHUB_ENV
            echo $BUILD_CACHE_ENTRY >> $GITHUB_ENV
            echo $TRANSFORM_CACHE_ENTRY >> $GITHUB_ENV
          else
            echo "Unknown mode: ${{ inputs.mode }}"
            exit 1
          fi
      shell: bash    
    - name: Setup Gradle
      if: github.event.inputs.mode != 'no caching'    
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: true
        add-job-summary: 'never'
        gradle-home-cache-excludes: ${{ env.GRADLE_HOME_CACHE_EXCLUDES}}
           
      env:
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: 'seed'
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ${{inputs.execution-number}}-${{inputs.variant}}

    - name: Execute Gradle build
      id : gradle-build
      run: |
           ./gradlew ${{ inputs.task }} ${{ inputs.extra-args }} -Dscan.tag.${{ inputs.run-id }} -Dscan.tag.${{ inputs.variant-prefix }}${{ inputs.variant }} -Dscan.tag."${{ inputs.mode }}" -Dscan.tag.experiment -Dscan.tag.${{inputs.experiment-id}} -Dscan.tag.${{inputs.experiment-id}}_variant_experiment_${{ inputs.variant }}
      shell: bash
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ inputs.api-key }}
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: 'seed'
        CI_URL_CACHE_NODE: ${{ inputs.cache-url }}
