name: 'Experiment runner'
inputs:
  task:
    required: true
  variant:
    required: true
  experiment-id:
    required: true
  api-key:
    required: true
  repository:
    required: true
  run-id:
    required: true
  jdk:
    required: false
    default: 17
  execution-number:
    required: true 

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.variant }}
    - uses: actions/setup-java@v4
      with:
        distribution: oracle
        java-version: ${{ inputs.jdk }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: true
        add-job-summary: 'never'
        gradle-home-cache-excludes: |
          caches/build-cache-1
      env:
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: 'seed'
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ${{inputs.execution-number}}-${{inputs.variant}}

    - name: Execute Gradle build
      id : gradle-build
      run: |
           ./gradlew ${{ inputs.task }}  -Dscan.tag.${{ inputs.run-id }} -Dscan.tag.${{ inputs.variant }} -Dscan.tag.experiment -Dscan.tag.${{inputs.experiment-id}} -Dscan.tag.${{inputs.experiment-id}}_variant_experiment_${{ inputs.variant }}
      shell: bash
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ inputs.api-key }}
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB: 'seed'
