name: 'GE Experiment Runner'
description: 'Exexutes with Gradle Profiler a scenario defined'
inputs:
  task:
    description: ""
    required: true
  warmups:
    description: "Number of build warmups"
    required: false
    default: 1
  iterations:
    description: "Number of iterations"
    required: false
    default: 5
  class:
    description: "Class to apply the abi change"
    required: false
  variant:
    description: "variant of the experiment, represents the branch"
    required: true
  experiment-id:
    description: ""
    required: true
  api-key:
    description: ""
    required: true
  repository:
    required: true
  runs:
    required: true
  jdk:
    required: false
    default: 17
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.variant }}
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ inputs.jdk }}
    - name: Execute Gradle build
      id : geapix
      run: |
           ## replace cache node if is required credentials
           if [ -f "cache_node.json" ]; then
              JSON_private_key_id=$(jq '.private_key_id = "${{secrets.CACHE_NODE_PRIVATE_KEY_ID}}"' cache-node.json)
              echo "$JSON_private_key_id" > cache-node.json
              JSON_private_key=$(jq '.private_key = "${{secrets.CACHE_NODE_PRIVATE_KEY}}"' cache-node.json)
              echo "$JSON_private_key" > cache-node.json
           fi
           ./gradlew ${{ inputs.task }}  -Dscan.tag.${{ inputs.runs }} -Dscan.tag.${{ inputs.variant }} -Dscan.tag.experiment -Dscan.tag.${{inputs.experiment-id}} -Dscan.tag.${{inputs.experiment-id}}_variant_experiment_${{ inputs.variant }}
      shell: bash           
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ inputs.api-key }}
