name: 'Experiment runner'
inputs:
  task:
    required: true
  variant:
    required: true
  experiment-id:
    required: true
  api-key:
    required: true
  repository:
    required: true
  run-id:
    required: true
  jdk:
    required: false
    default: 17
  mode:
    required: true
  extra-args:
    required: true  
  cache-url:
    required: false      
  

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.variant }}
    - uses: actions/setup-java@v4
      with:
        distribution: oracle
        java-version: ${{ inputs.jdk }}
    - name: Set Gradle Cache Excludes
      id: set-cache-excludes
      run: |
        if [[ "${{ inputs.mode }}" == "remote cache" ]]; then
          echo "GRADLE_HOME_CACHE_EXCLUDES='**'" >> $GITHUB_ENV
        elif [[ "${{ inputs.mode }}" == "dependencies cache" ]]; then
          echo "GRADLE_HOME_CACHE_EXCLUDES='caches/build-cache-1\ncaches/8.9/transforms'" >> $GITHUB_ENV
        elif [[ "${{ inputs.mode }}" == "local build cache + dependencies cache" ]]; then
          echo "GRADLE_HOME_CACHE_EXCLUDES=" >> $GITHUB_ENV
        elif [[ "${{ inputs.mode }}" == "remote cache + dependencies cache" ]]; then
          echo "GRADLE_HOME_CACHE_EXCLUDES=caches/build-cache-1" >> $GITHUB_ENV
        else
          echo "Unknown mode: ${{ inputs.mode }}"
          exit 1
        fi
      shell: bash    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      if: github.event.inputs.mode != 'remote cache'
      with:
        cache-write-only: true
        cache-overwrite-existing: true
        add-job-summary: 'never'
        gradle-home-cache-excludes: |
           ${{ env.GRADLE_HOME_CACHE_EXCLUDES }}
      env:
        GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE: ${{inputs.experiment-id}}-${{inputs.variant}}
    - name: Execute Gradle build
      id : gradle-build
      run: |
           ./gradlew ${{ inputs.task }} ${{ inputs.extra-args }} -Dscan.tag.seed_${{ inputs.variant }} -Dscan.tag.seed -Dscan.tag.seed_${{inputs.experiment-id}}
      shell: bash
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ inputs.api-key }}
        CI_URL_CACHE_NODE: ${{ inputs.cache-url }}
    - uses: actions/checkout@v4
            
