name: Experiment

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        default: "cdsap/ExperimentGradle8.9"
      variantA:
        required: true
        default: "gradle_8_8"
      variantB:
        required: true
        default: "gradle_8_9"
      task:
        default: ":core:model:compileKotlin"
        required: true
      iterations:
        default: 10
        required: true
      mode:
        description: "Type of execution relative to caching"
        type: choice
        required: true
        default: 'dependencies cache'
        options:
          - 'no caching'
          - 'dependencies cache'
          - 'local build cache + dependencies cache' 
          - 'remote build cache + dependencies cache'
          - 'remote build cache'
      taskpathreport:
        description: "Include experiment results by task path"
        type: choice
        required: true
        default: 'true'
        options:
          - true
          - false
      kotlinreport:
        description: "Include Kotlin Build reports in the experiment results"
        type: choice
        required: true
        default: 'true'
        options:
          - true
          - false
      java-variant-a:
        description: "Java version variant a"
        default: '17'
      java-variant-b:
        description: "Java version variant b"
        default: '17'


run-name: "${{ github.event.inputs.repository }}-${{ github.event.inputs.variantA }}-${{ github.event.inputs.variantB }}-${{ github.event.inputs.task }}"

jobs:
  seed:
    if: github.event.inputs.mode != 'no caching'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ "${{ github.event.inputs.variantA }}", "${{ github.event.inputs.variantB }}" ]
    outputs:
      skip: ${{ github.event.inputs.mode == 'no caching' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/runner-seed
        with:
          task: "${{ github.event.inputs.task }}"
          mode: "${{ github.event.inputs.mode }}"
          experiment-id: "${{ github.run_number }}"
          variant: ${{ matrix.variant }}
          run-id: 1
          api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          repository: ${{ github.event.inputs.repository }}
          jdk: ${{ (matrix.variant == github.event.inputs.variantA) && github.event.inputs.java-variant-a || (matrix.variant == github.event.inputs.variantB) && github.event.inputs.java-variant-b }}

  iterations:
    needs: [seed]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ "${{ github.event.inputs.variantA }}", "${{ github.event.inputs.variantB }}" ]
        runs: ${{ fromJson(needs.seed.outputs.iterations) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/runner
        with:
          task: "${{ github.event.inputs.task }}"
          mode: "${{ github.event.inputs.mode }}"
          experiment-id: "no-profile-${{ github.run_number }}"
          execution-number: ${{ github.run_number }}
          variant: ${{ matrix.variant }}
          api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          repository: ${{ github.event.inputs.repository }}
          jdk: ${{ (matrix.variant == github.event.inputs.variantA) && github.event.inputs.java-variant-a || (matrix.variant == github.event.inputs.variantB) && github.event.inputs.java-variant-b }}

  execution:
    needs: ${{ github.event.inputs.mode != 'no caching' && 'seed,iterations' || 'iterations' }}
    if: ${{ github.event.inputs.mode == 'no caching' || github.event.inputs.mode != 'no caching' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ "${{ github.event.inputs.variantA }}", "${{ github.event.inputs.variantB }}" ]
        runs: ${{ fromJson(needs.iterations.outputs.iterations) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/runner
        with:
          task: "${{ github.event.inputs.task }}"
          mode: "${{ github.event.inputs.mode }}"
          experiment-id: "no-profile-${{ github.run_number }}"
          execution-number: ${{ github.run_number }}
          variant: ${{ matrix.variant }}
          api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          repository: ${{ github.event.inputs.repository }}
          jdk: ${{ (matrix.variant == github.event.inputs.variantA) && github.event.inputs.java-variant-a || (matrix.variant == github.event.inputs.variantB) && github.event.inputs.java-variant-b }}

  report:
    needs: [execution]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/report
        with:
          task: "${{ github.event.inputs.task }}"
          experiment-id: "no-profile-${{ github.run_number }}"
          tags: "${{ github.event.inputs.variantA }},${{ github.event.inputs.variantB }}"
          api-key: ${{ secrets.GE_API_KEY }}
          url: ${{ secrets.GE_URL }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          profile: false
          taskpathreport: ${{ github.event.inputs.taskpathreport }}
          processreport: true
          kotlinreport: ${{ github.event.inputs.kotlinreport }}