name: pagan_no_profile
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
      variantA:
        required: true
      variantB: 
        required: true 
      task: 
        required: true 
      class: 
        required: false
      iterations:
        required: true
  

jobs:
    iterations:
      name: Generate versions
      runs-on: ubuntu-latest
      steps:
         - id: calculate_iterations
           run: |
            values=""
            for i in {1..5}
            do  
                values="$values,  $i"
            done
            echo "iterations=$(values | tail -c+2)"   >> $GITHUB_OUTPUT
      outputs:
         matrix: ${{ steps.calculate_iterations.outputs.iterations }}
    
    runners:
      needs: [iterations]
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - id: runner
           run: |
            echo ${{ needs.iterations.outputs.iterations }}
