name: pagan
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
      variantA:
        required: true
      variantB: 
        required: true 
      task: 
        required: true 

jobs:
    runners:
      strategy:
        matrix:
          version: ["${{ github.event.inputs.variantA }}","${{ github.event.inputs.variantB }}"]
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - id: foo
           uses: cdsap/ge-experiment-runner@main
           with:
             task: "${{ github.event.inputs.task }}"
             iterations: 5
             experiment-id: ${{github.run_number}}
             variant: ${{ matrix.version }}
             api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
             repository: ${{ github.event.inputs.repository }}
    report:
      runs-on: "ubuntu-latest"
      needs: [ runners]
      steps:
         - uses: actions/checkout@v3
         - id: fooa
           uses: cdsap/ge-experiment-report@main
           with:
             task: "assembleDebug"
             experiment-id: ${{github.run_number}}
             tags: "${{ github.head_ref }}, test_325"
             project: "nowinandroid"
             api-key: ${{ secrets.GE_API_KEY }}
             url: ${{ secrets.GE_URL }}
             gh_token: ${{secrets.GITHUB_TOKEN}}