name: pagan
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
      variantA:
        required: true
      variantB: 
        required: true 
      task: 
        required: true 
      class: 
        required: false
      iterations:
        required: false
  
run-name: "profile-${{ github.event.inputs.repository }}-${{ github.event.inputs.variantA }}-${{ github.event.inputs.variantB }}-${{ github.event.inputs.task }}"

jobs:
    runners:
      strategy:
        matrix:
          version: ["${{ github.event.inputs.variantA }}","${{ github.event.inputs.variantB }}"]
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - uses: ./.github/workflows/runner-gradle-profiler
           with:
             task: "${{ github.event.inputs.task }}"
             iterations: ${{ github.event.inputs.iterations }}
             experiment-id: ${{github.run_number}}
             variant: ${{ matrix.version }}
             class: ${{ github.event.inputs.class }}
             api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
             repository: ${{ github.event.inputs.repository }}
         - uses: actions/checkout@v3             
    report:
      runs-on: "ubuntu-latest"
      needs: [ runners]
      steps:
         - uses: actions/checkout@v3
         - uses: ./.github/workflows/report
           with:
             task: "${{ github.event.inputs.task }}"
             experiment-id: ${{github.run_number}}
             tags: "${{ github.event.inputs.variantA }},${{ github.event.inputs.variantB }}"
             project: "nowinandroid"
             api-key: ${{ secrets.GE_API_KEY }}
             url: ${{ secrets.GE_URL }}
             profile: true
             gh_token: ${{secrets.GITHUB_TOKEN}}
         - uses: actions/checkout@v3             
             