name: pagan_no_profile
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        default: "cdsap/K2nowinandroid"
      variantA:
        required: true
        default: "main"
      variantB: 
        required: true
        default: "kotlin_1_9" 
      task: 
        default: ":help"
        required: true 
      class: 
        required: false
      iterations:
        default: 1
        required: true
  

jobs:
    iterations:
      name: Generate versions
      runs-on: ubuntu-latest
      steps:
         - id: calculate_iterations
           run: |
            iterations=" ["
            for i in {1..${{ github.event.inputs.iterations }}}
            do
              if [ $i == 1 ]
              then
                iterations="$iterations \"$i\""
              else
                iterations="$iterations  , \"$i\""
              fi
            done
            iterations="$iterations ]"
            echo "iterations=$iterations" >> $GITHUB_OUTPUT
            echo $GITHUB_OUTPUT
      outputs:
         iterations: ${{ steps.calculate_iterations.outputs.iterations }}
    
    execution:
      needs: [iterations]
      strategy:
        matrix:
          variant: ["${{ github.event.inputs.variantA }}","${{ github.event.inputs.variantB }}"]
          runs:   ${{ fromJson(needs.iterations.outputs.iterations) }} 
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - uses: ./.github/workflows/runner
           with:
             task: "${{ github.event.inputs.task }}"
             iterations: ${{ github.event.inputs.iterations }}
             experiment-id: ${{github.run_number}}
             variant: ${{ matrix.variant }}
             runs: ${{ matrix.runs }}
             class: ${{ github.event.inputs.class }}
             api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
             repository: ${{ github.event.inputs.repository }}
         - uses: actions/checkout@v3
    report:
      runs-on: "ubuntu-latest"
      needs: [ execution]
      steps:
         - uses: actions/checkout@v3
         - id: report
           uses: cdsap/ge-experiment-report@main
           with:
             task: "${{ github.event.inputs.task }}"
             experiment-id: ${{github.run_number}}
             tags: "${{ github.event.inputs.variantA }},${{ github.event.inputs.variantB }}"
             project: "nowinandroid"
             api-key: ${{ secrets.GE_API_KEY }}
             url: ${{ secrets.GE_URL }}
             gh_token: ${{secrets.GITHUB_TOKEN}}         
             profile: false