name: pagan_no_profile
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
      variantA:
        required: true
      variantB: 
        required: true 
      task: 
        required: true 
      class: 
        required: false
      iterations:
        required: true
  

jobs:
    iterations:
      name: Generate versions
      runs-on: ubuntu-latest
      steps:
         - id: calculate_iterations
           run: |
            iterations=""
            for i in {1..${{ github.event.inputs.iterations }}}
            do
              if [ $i == 1 ]
              then
                iterations="$i"
              else
                iterations="$iterations,  $i"
              fi
            done
            echo "iterations=$iterations" >> $GITHUB_OUTPUT
            echo $GITHUB_OUTPUT
      outputs:
         iterations: ${{ steps.calculate_iterations.outputs.iterations }}
    
    runners:
      needs: [iterations]
      strategy:
        matrix:
          variant: ["${{ github.event.inputs.variantA }}","${{ github.event.inputs.variantB }}"]
          run: [ "${{ needs.iterations.outputs.iterations }}"] 
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - id: runner
           run: |
            echo ${{ matrix.run }}
            echo ${{ matrix.variant }}
