name: pagan
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
      variantA:
        required: true
      variantB: 
        required: true 
      task: 
        required: true 
      class: 
        required: false
      iterations:
        required: false
  

jobs:
    runners:
      strategy:
        matrix:
          version: ["${{ github.event.inputs.variantA }}","${{ github.event.inputs.variantB }}"]
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - id: runner
           uses: cdsap/ge-experiment-runner@main
           with:
             task: "${{ github.event.inputs.task }}"
             iterations: ${{ github.event.inputs.iterations }}
             experiment-id: ${{github.run_number}}
             variant: ${{ matrix.version }}
             class: ${{ github.event.inputs.class }}
             api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
             repository: ${{ github.event.inputs.repository }}
    report:
      runs-on: "ubuntu-latest"
      needs: [ runners]
      steps:
         - uses: actions/checkout@v3
         - id: report
           uses: cdsap/ge-experiment-report@main
           with:
             task: "${{ github.event.inputs.task }}"
             experiment-id: ${{github.run_number}}
             tags: "${{ github.event.inputs.variantA }},${{ github.event.inputs.variantB }}"
             project: "nowinandroid"
             api-key: ${{ secrets.GE_API_KEY }}
             url: ${{ secrets.GE_URL }}
             profile: true
             gh_token: ${{secrets.GITHUB_TOKEN}}
             